// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tms

import "encoding/json"
import "fmt"

// The limits for an individual tile matrix of a TileSet's TileMatrixSet, as
// defined in the OGC 2D TileMatrixSet and TileSet Metadata Standard
type TileMatrixLimitsJson struct {
	// MaxTileCol corresponds to the JSON schema field "maxTileCol".
	MaxTileCol int `json:"maxTileCol" yaml:"maxTileCol" mapstructure:"maxTileCol"`

	// MaxTileRow corresponds to the JSON schema field "maxTileRow".
	MaxTileRow int `json:"maxTileRow" yaml:"maxTileRow" mapstructure:"maxTileRow"`

	// MinTileCol corresponds to the JSON schema field "minTileCol".
	MinTileCol int `json:"minTileCol" yaml:"minTileCol" mapstructure:"minTileCol"`

	// MinTileRow corresponds to the JSON schema field "minTileRow".
	MinTileRow int `json:"minTileRow" yaml:"minTileRow" mapstructure:"minTileRow"`

	// TileMatrix corresponds to the JSON schema field "tileMatrix".
	TileMatrix string `json:"tileMatrix" yaml:"tileMatrix" mapstructure:"tileMatrix"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TileMatrixLimitsJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["maxTileCol"]; raw != nil && !ok {
		return fmt.Errorf("field maxTileCol in TileMatrixLimitsJson: required")
	}
	if _, ok := raw["maxTileRow"]; raw != nil && !ok {
		return fmt.Errorf("field maxTileRow in TileMatrixLimitsJson: required")
	}
	if _, ok := raw["minTileCol"]; raw != nil && !ok {
		return fmt.Errorf("field minTileCol in TileMatrixLimitsJson: required")
	}
	if _, ok := raw["minTileRow"]; raw != nil && !ok {
		return fmt.Errorf("field minTileRow in TileMatrixLimitsJson: required")
	}
	if _, ok := raw["tileMatrix"]; raw != nil && !ok {
		return fmt.Errorf("field tileMatrix in TileMatrixLimitsJson: required")
	}
	type Plain TileMatrixLimitsJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.MaxTileCol {
		return fmt.Errorf("field %s: must be >= %v", "maxTileCol", 0)
	}
	if 0 > plain.MaxTileRow {
		return fmt.Errorf("field %s: must be >= %v", "maxTileRow", 0)
	}
	if 0 > plain.MinTileCol {
		return fmt.Errorf("field %s: must be >= %v", "minTileCol", 0)
	}
	if 0 > plain.MinTileRow {
		return fmt.Errorf("field %s: must be >= %v", "minTileRow", 0)
	}
	*j = TileMatrixLimitsJson(plain)
	return nil
}
